name: 'EXAMPLE Orchest test fo modified project'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.monorepo-packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v3
      - id: monorepo-packages
        uses: ./ # vgpastor/monorepo-updated-packages@v1.0
        with:
          folder: example/sourceTest
      - name: Debug
        run: |
          echo ${{ steps.monorepo-packages.outputs.packages }}          
          echo ${{ fromJson(steps.monorepo-packages.outputs.packages) }}
          echo ${{ fromJson(steps.monorepo-packages.outputs.packages) | length }}
  exec:
    needs: [ setup ]
    runs-on: ubuntu-latest
    if: ${{ fromJson(needs.setup.outputs.packages) | length > 0 }}
    strategy:
      matrix:
        project: ${{ fromJson(needs.setup.outputs.packages) }}
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd example/sourceTest/${{ matrix.project }} && npm install
      - run: cd example/sourceTest/${{ matrix.project }} && npm ci
      - run: cd example/sourceTest/${{ matrix.project }} && npm run build --if-present
      - run: cd example/sourceTest/${{ matrix.project }} && npm test

